ZPI-58: Added error 500 to endpoints, fix k8s update body, remove unused params from k8s list
ZPI-2024-25/KubernetesAccessManager pull request #12
Opened 2024-10-19 08:28 UTC by samuelus

2024-10-19 10:27 UTC, Ninja00Shadow requested changes

2024-10-19 10:27 UTC, Ninja00Shadow commented on backend/models/model_user.go
I don't think permissions as an array is good. In this way, we would have different permision levels for all resources. It should be json, in which we have resource type and level of access to it.

2024-10-19 10:27 UTC, Ninja00Shadow commented on backend/models/model_user_status.go
Same here as in model_user

2024-10-19 12:43 UTC, samuelus commented on backend/models/model_user.go
Moim zdaniem to nie ma tak, że dobrze albo że nie dobrze. Gdybym miał powiedzieć, co cenię w życiu najbardziej, powiedziałbym, że ludzi. 
When Marek and I get to how keycloack works, then we'll change it to make it right.

2024-10-19 12:44 UTC, samuelus commented on backend/models/model_user_status.go
Same here as in model_user

2024-10-20 11:15 UTC, samuelus commented on backend/models/model_user_status.go
Moim zdaniem to nie ma tak, że dobrze albo że nie dobrze. Gdybym miał powiedzieć, co cenię w życiu najbardziej, powiedziałbym, że ludzi.
When Marek and I get to how keycloack works, then we'll change it to make it right.

2024-10-20 12:13 UTC, Ninja00Shadow approved these changes

2024-10-20 12:15 UTC, merged